# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d01ae82f4e7a19cf66d74751aae871002f95f416070388edd71520de6f3553ad04866524356c4817d23189c0a09b51d194e384f7c716488800da27347721705e

test:
  secret_key_base: 7f081e5578da8d21bf45014304a13bbb2a399076e7d60b05fd4c77ae930715d3940ffabdef33d55a0f0e39fcfca607a8a2f4d5444b874e008516baedb3b91454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
